// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KOUdnaDaco9rH0ehVGxcV3GQxGjmNfw',
    appId: '1:686642890891:web:51e1d1c3e80c88e103ec8e',
    messagingSenderId: '686642890891',
    projectId: 'rojgar-e7c30',
    authDomain: 'rojgar-e7c30.firebaseapp.com',
    storageBucket: 'rojgar-e7c30.appspot.com',
    measurementId: 'G-WPTCPN1KC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMg1RbW9aJ6FkYSDbG_mn0LrixDTTu_ic',
    appId: '1:686642890891:android:f1c198459a44f00903ec8e',
    messagingSenderId: '686642890891',
    projectId: 'rojgar-e7c30',
    storageBucket: 'rojgar-e7c30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2JSvB3zuyur7lYFLBy8RS3n3JyGPnBW0',
    appId: '1:686642890891:ios:a7e6e300f265627503ec8e',
    messagingSenderId: '686642890891',
    projectId: 'rojgar-e7c30',
    storageBucket: 'rojgar-e7c30.appspot.com',
    iosClientId: '686642890891-r041spelo20licavucl97a7o2mp244u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rojgar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2JSvB3zuyur7lYFLBy8RS3n3JyGPnBW0',
    appId: '1:686642890891:ios:543ded397f88e41f03ec8e',
    messagingSenderId: '686642890891',
    projectId: 'rojgar-e7c30',
    storageBucket: 'rojgar-e7c30.appspot.com',
    iosClientId: '686642890891-l1hqv4uesfh2jcoiilmrc6g3pnbhgan8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rojgar.RunnerTests',
  );
}
